kind: pipeline
name: default

steps:
- name: plan
  image: hashicorp/terraform:0.12.9
  environment:
      AWS_ACCESS_KEY_ID:
          from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
          from_secret: AWS_SECRET_ACCESS_KEY
          
  commands:
  - terraform init
  - terraform validate
  - terraform plan

  when:
    branch:
      exclude:
      - master

#- name: slack
#  image: plugins/slack
#  settings:
#    webhook:
#      from_secret: slack_webhook
#    channel: droneci

- name: apply
  image: hashicorp/terraform:0.12.9
  environment:
      AWS_ACCESS_KEY_ID:
          from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
          from_secret: AWS_SECRET_ACCESS_KEY
          
  commands:
  - terraform init
  - terraform apply -auto-approve

  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: destroy	
  image: hashicorp/terraform:0.12.9	
  environment:	
      AWS_ACCESS_KEY_ID:	
          from_secret: AWS_ACCESS_KEY_ID	
      AWS_SECRET_ACCESS_KEY:	
          from_secret: AWS_SECRET_ACCESS_KEY	

  commands:	
  - terraform init	
  - terraform destroy -auto-approve	

  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
