kind: pipeline
name: default

steps:
- name: plan
  image: hashicorp/terraform:light
  environment:
      AWS_ACCESS_KEY_ID:
          from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
          from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION:
          from_secret: AWS_DEFAULT_REGION
          
  commands:
  - terraform init
  - terraform validate
  - terraform plan

#- name: slack
#  image: plugins/slack
#  settings:
#    webhook:
#      from_secret: slack_webhook
#    channel: droneci

- name: deploy
  image: hashicorp/terraform:light
  environment:
      AWS_ACCESS_KEY_ID:
          from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
          from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION:
          from_secret: AWS_DEFAULT_REGION
          
  commands:
  - terraform init
  - terraform validate
  - terraform apply -auto-approve

  when:
    branch:
    - master

- name: destroy	
  image: hashicorp/terraform:light	
  environment:	
      AWS_ACCESS_KEY_ID:	
          from_secret: AWS_ACCESS_KEY_ID	
      AWS_SECRET_ACCESS_KEY:	
          from_secret: AWS_SECRET_ACCESS_KEY	
      AWS_DEFAULT_REGION:	
          from_secret: AWS_DEFAULT_REGION	

  commands:	
  - terraform -v	
  - terraform init	
  - terraform validate	
  - terraform destroy -auto-approve	

   when:	
    branch:	
    - master
